# Human readable title of application.
title: Alibaba Cloud Provider

overviewShort: The Alibaba Cloud Crossplane provider enables experimental infrastructure management for the Alibaba Cloud.
overview: |-
  The Alibaba Cloud Crossplane Provider adds experimental support for managing Alibaba Cloud infrastructure in Kubernetes.

# Markdown description of this entry
readme: |
 `provider-alibaba` is a Crossplane infrastructure for the [Alibaba Cloud](https://alibabacloud.com).
 The package that is built from the source code in this repository can be installed into a Crossplane control plane and adds the following new functionality:

 * Custom Resource Definitions (CRDs) that model Alibaba Cloud infrastructure and services
 * Controllers to provision these resources in Alibaba Cloud based on the users desired state captured in CRDs they create
 * Implementations of Crossplane's portable resource abstractions, enabling Alibaba Cloud resources to fulfill a user's general need for cloud services

# Maintainer names and emails.
maintainers:
- name: Nic Cope
  email: negz@upbound.io

# Owner names and emails.
owners:
- name: Nic Cope
  email: negz@upbound.io

# Human readable company name
company: Crossplane

# Primary category describing this package
category: Infrastructure

# Type of package: Provider, Stack, or Application
packageType: Provider

# Keywords that describe this application and help search indexing
keywords:
- "google"
- "alibaba"
- "infrastructure"

# Links to more information about the application (about page, source code, etc.)
website: "https://crossplane.io"
source: "https://github.com/crossplane/provider-alibaba"

# RBAC ClusterRoles will be generated permitting this package to use all verbs on all
# resources in the groups listed below.
permissionScope: Cluster
dependsOn:
- crd: '*.cache.crossplane.io/v1alpha1'
- crd: '*.compute.crossplane.io/v1alpha1'
- crd: '*.database.crossplane.io/v1alpha1'
- crd: '*.core.crossplane.io/v1alpha1'
- crd: '*.storage.crossplane.io/v1alpha1'

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
